<?php

namespace ALBEIRO\PartiturasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartiturasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartiturasRepository extends EntityRepository
{
}
